apiVersion: v1
kind: Pod
metadata:
  name: voting-pod
  labels:
    name: voting-pod
    app: voting-app
spec:
  containers:
    - name: voting-cont
      image: dockersamples/examplevotingapp_vote
      ports:
        - containerPort: 80

