apiVersion: v1
kind: Service
metadata:
  name: vote-app-service
  labels:
    name: vote-app-service
    app: voting-app
spec:
  type: LoadBalancer
  ports:
    - targetPort: 80
      port: 80
  selector:
    name: voting-pod
    app: voting-app